"""
Inventory optimization using a Periodic Review (Order-Up-To) policy.

Business Assumptions
--------------------
- Inventory is not available in the Walmart dataset and is therefore simulated.
- Review period = 1 week.
- Lead time = 2 weeks.
- Target service level = 95%.
- Holding cost = $0.25/unit/week.
- Ordering cost = $50/order.
- Initial inventory = 120% of forecast demand over the protection interval.

The replenishment system uses demand forecasts generated by the forecasting
module and converts them into replenishment decisions.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd
from scipy.stats import norm


@dataclass
class InventoryMetrics:
    """Summary metrics produced by the inventory simulation."""

    fill_rate: float
    stockout_rate: float
    total_stockout_volume: float
    average_inventory: float
    average_order_quantity: float
    holding_cost: float
    ordering_cost: float
    total_inventory_cost: float


class InventorySimulator:
    """
    Simulate inventory using a periodic review Order-Up-To policy.
    """

    def __init__(
        self,
        review_period: int = 1,
        lead_time: int = 2,
        service_level: float = 0.95,
        initial_inventory_multiplier: float = 1.2,
        holding_cost_per_unit: float = 0.25,
        ordering_cost: float = 50.0,
    ):

        self.review_period = review_period
        self.lead_time = lead_time
        self.service_level = service_level

        self.initial_inventory_multiplier = (
            initial_inventory_multiplier
        )

        self.holding_cost_per_unit = holding_cost_per_unit
        self.ordering_cost = ordering_cost

        self.z = float(norm.ppf(service_level))

    # --------------------------------------------------------
    # Forecast Error
    # --------------------------------------------------------

    def calculate_forecast_error(
        self,
        actual: np.ndarray,
        predicted: np.ndarray,
    ) -> float:
        """
        Standard deviation of forecast errors.
        """

        errors = actual - predicted

        return float(np.std(errors, ddof=1))

    # --------------------------------------------------------
    # Safety Stock
    # --------------------------------------------------------

    def calculate_safety_stock(
        self,
        sigma: float,
    ) -> float:
        """
        Safety Stock

        SS = z * sigma * sqrt(R + L)
        """

        return (
            self.z
            * sigma
            * np.sqrt(
                self.review_period
                + self.lead_time
            )
        )

    # --------------------------------------------------------
    # Target Inventory
    # --------------------------------------------------------

    def calculate_target_inventory(
        self,
        future_forecast: np.ndarray,
        safety_stock: float,
    ) -> float:
        """
        Order-Up-To level.

        Uses the sum of forecast demand over the protection interval
        instead of a single global average.
        """

        expected_demand = future_forecast.sum()

        return expected_demand + safety_stock

    # --------------------------------------------------------
    # Order Quantity
    # --------------------------------------------------------

    def calculate_order_quantity(
        self,
        target_inventory: float,
        current_inventory: float,
        pipeline_inventory: float,
    ) -> float:
        """
        Order quantity.

        Inventory Position =
            On-hand inventory
            + pipeline inventory.
        """

        inventory_position = (
            current_inventory
            + pipeline_inventory
        )

        return max(
            0.0,
            target_inventory - inventory_position,
        )
    
    # Simulation

    def simulate(
        self,
        forecast_df: pd.DataFrame,
        actual_col: str = "Actual_Sales",
        predicted_col: str = "Predicted_Sales",
        demand_col: str = "Demand_For_Replenishment",
    ) -> tuple[pd.DataFrame, InventoryMetrics]:
        """
        Simulate inventory dynamics for every Store-Department pair.

        Returns
        -------
        simulation_df
            DataFrame containing inventory history.

        metrics
            Inventory KPIs.
        """

        required = {
            "Store",
            "Dept",
            "Date",
            actual_col,
            predicted_col,
            demand_col,
        }

        missing = required - set(forecast_df.columns)

        if missing:
            raise KeyError(
                f"Missing required columns: {sorted(missing)}"
            )

        simulation_results = []

        total_demand = 0.0
        total_fulfilled = 0.0

        total_stockout_volume = 0.0

        holding_cost = 0.0
        ordering_cost = 0.0

        total_orders = []

        # --------------------------------------------------

        for (store, dept), group in forecast_df.groupby(
            ["Store", "Dept"]
        ):

            group = (
                group.sort_values("Date")
                .copy()
                .reset_index(drop=True)
            )

            actual = group[actual_col].to_numpy()

            predicted = group[predicted_col].to_numpy()

            demand = group[demand_col].to_numpy()

            sigma = self.calculate_forecast_error(
                actual,
                predicted,
            )

            safety_stock = self.calculate_safety_stock(
                sigma
            )

            protection_period = (
                self.review_period
                + self.lead_time
            )

            first_forecast = max(
                demand[0],
                0,
            )

            inventory = (
                self.initial_inventory_multiplier
                * first_forecast
                * protection_period
            )

            pipeline_orders: list[tuple[int, float]] = []

            beginning_inventory = []

            ending_inventory = []

            inventory_levels = []

            order_quantity = []

            target_inventory = []

            stockout = []

            stockout_volume = []

            # ----------------------------------------------

            for t in range(len(group)):

                arrivals = sum(
                    qty
                    for arrival_week, qty
                    in pipeline_orders
                    if arrival_week == t
                )

                pipeline_orders = [
                    (arrival_week, qty)
                    for arrival_week, qty
                    in pipeline_orders
                    if arrival_week != t
                ]

                inventory += arrivals

                beginning_inventory.append(inventory)

                # ------------------------------------------
                # Dynamic Order-Up-To level
                # ------------------------------------------

                horizon = demand[
                    t:
                    t + protection_period
                ]

                target = self.calculate_target_inventory(
                    horizon,
                    safety_stock,
                )

                target_inventory.append(target)

                # ------------------------------------------

                current_pipeline = sum(
                    qty
                    for _, qty
                    in pipeline_orders
                )

                order = self.calculate_order_quantity(
                    target,
                    inventory,
                    current_pipeline,
                )

                order_quantity.append(order)

                if order > 0:

                    pipeline_orders.append(
                        (
                            t + self.lead_time,
                            order,
                        )
                    )

                    ordering_cost += (
                        self.ordering_cost
                    )

                # ------------------------------------------
                # Fulfil demand
                # ------------------------------------------

                fulfilled = min(
                    inventory,
                    demand[t],
                )

                shortfall = max(
                    0.0,
                    demand[t] - fulfilled,
                )

                inventory -= fulfilled

                inventory = max(
                    inventory,
                    0.0,
                )

                ending_inventory.append(
                    inventory
                )

                inventory_levels.append(
                    inventory
                )

                stockout.append(
                    int(shortfall > 0)
                )

                stockout_volume.append(
                    shortfall
                )

                total_demand += demand[t]

                total_fulfilled += fulfilled

                total_stockout_volume += shortfall

                holding_cost += (
                    inventory
                    * self.holding_cost_per_unit
                )

                total_orders.append(order)

            group["Beginning_Inventory"] = (
                beginning_inventory
            )

            group["Target_Inventory"] = (
                target_inventory
            )

            group["Order_Quantity"] = (
                order_quantity
            )

            group["Ending_Inventory"] = (
                ending_inventory
            )

            group["Inventory_Level"] = (
                inventory_levels
            )

            group["Safety_Stock"] = (
                safety_stock
            )

            group["Stockout"] = stockout

            group["Stockout_Volume"] = (
                stockout_volume
            )

            simulation_results.append(
                group
            )

        simulation_df = (
            pd.concat(
                simulation_results,
                ignore_index=True,
            )
            .sort_values(
                ["Store", "Dept", "Date"]
            )
        )

        metrics = InventoryMetrics(
            fill_rate=(
                total_fulfilled
                / total_demand
                if total_demand > 0
                else 0
            ),
            stockout_rate=float(
                simulation_df["Stockout"].mean()
            ),
            total_stockout_volume=(
                total_stockout_volume
            ),
            average_inventory=float(
                simulation_df[
                    "Ending_Inventory"
                ].mean()
            ),
            average_order_quantity=(
                float(np.mean(total_orders))
                if total_orders
                else 0.0
            ),
            holding_cost=holding_cost,
            ordering_cost=ordering_cost,
            total_inventory_cost=(
                holding_cost
                + ordering_cost
            ),
        )

        return simulation_df, metrics